CREATE TABLE IF NOT EXISTS `meta_new` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `period` int(11) NOT NULL DEFAULT '0',
  `agent_id` int(11) NOT NULL,
  `ramo` int(11) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `year` year(4) NOT NULL,

  `efectividad` float NOT NULL DEFAULT '0',

  `primas-cuarto-primer` float NOT NULL DEFAULT '0',
  `primas-meta-1` float NOT NULL DEFAULT '0',
  `primas-meta-2` float NOT NULL DEFAULT '0',
  `primas-meta-3` float NOT NULL DEFAULT '0',
  `primas-meta-4` float NOT NULL DEFAULT '0',
  `primas-meta-5` float NOT NULL DEFAULT '0',
  `primas-meta-6` float NOT NULL DEFAULT '0',
  `primas-meta-7` float NOT NULL DEFAULT '0',
  `primas-meta-8` float NOT NULL DEFAULT '0',
  `primas-meta-9` float NOT NULL DEFAULT '0',
  `primas-meta-10` float NOT NULL DEFAULT '0',
  `primas-meta-11` float NOT NULL DEFAULT '0',
  `primas-meta-12` float NOT NULL DEFAULT '0',
  `primas-negocios-meta-1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-8` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-9` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-10` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-11` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-negocios-meta-12` smallint(5) unsigned NOT NULL DEFAULT '0',

  `primas-segund-primer` float NOT NULL DEFAULT '0',
  `primas-solicitud-meta-1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-8` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-9` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-10` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-11` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-solicitud-meta-12` smallint(5) unsigned NOT NULL DEFAULT '0',
  `primas-tercer-primer` float NOT NULL DEFAULT '0',

  `primas_promedio` float NOT NULL DEFAULT '0',
  `primaspromedio` float NOT NULL DEFAULT '0',
  `prima_total_anual` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `ramo` (`ramo`),
  KEY `agent_id` (`agent_id`),
  KEY `year` (`year`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `simulator_new` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `period` int(11) NOT NULL DEFAULT '0',
  `agent_id` int(11) NOT NULL,
  `ramo` int(11) NOT NULL,
  `last_updated` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `year` year(4) NOT NULL,
  `bonoAplicado_1` float NOT NULL DEFAULT '0',
  `bonoAplicado_2` float NOT NULL DEFAULT '0',
  `bonoAplicado_3` float NOT NULL DEFAULT '0',
  `bonoAplicado_4` float NOT NULL DEFAULT '0',
  `comisionVentaInicial_1` float NOT NULL DEFAULT '0',
  `comisionVentaInicial_2` float NOT NULL DEFAULT '0',
  `comisionVentaInicial_3` float NOT NULL DEFAULT '0',
  `comisionVentaInicial_4` float NOT NULL DEFAULT '0',
  `comisionVentaRenovacion_1` float NOT NULL DEFAULT '0',
  `comisionVentaRenovacion_2` float NOT NULL DEFAULT '0',
  `comisionVentaRenovacion_3` float NOT NULL DEFAULT '0',
  `comisionVentaRenovacion_4` float NOT NULL DEFAULT '0',
  `efectividad` float NOT NULL DEFAULT '0',
  `ingresoBonoProductividad_1` float NOT NULL DEFAULT '0',
  `ingresoBonoProductividad_2` float NOT NULL DEFAULT '0',
  `ingresoBonoProductividad_3` float NOT NULL DEFAULT '0',
  `ingresoBonoProductividad_4` float NOT NULL DEFAULT '0',
  `ingresoBonoRenovacion` float NOT NULL DEFAULT '0',
  `ingresoBonoRenovacion_1` float NOT NULL DEFAULT '0',
  `ingresoBonoRenovacion_2` float NOT NULL DEFAULT '0',
  `ingresoBonoRenovacion_3` float NOT NULL DEFAULT '0',
  `ingresoBonoRenovacion_4` float NOT NULL DEFAULT '0',
  `ingresoComisionesVentaInicial_1` float NOT NULL DEFAULT '0',
  `ingresoComisionesVentaInicial_2` float NOT NULL DEFAULT '0',
  `ingresoComisionesVentaInicial_3` float NOT NULL DEFAULT '0',
  `ingresoComisionesVentaInicial_4` float NOT NULL DEFAULT '0',
  `ingresoComisionRenovacion_1` float NOT NULL DEFAULT '0',
  `ingresoComisionRenovacion_2` float NOT NULL DEFAULT '0',
  `ingresoComisionRenovacion_3` float NOT NULL DEFAULT '0',
  `ingresoComisionRenovacion_4` float NOT NULL DEFAULT '0',

  `noNegocios` smallint(5) unsigned NOT NULL DEFAULT '0',
  `noNegocios_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `noNegocios_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `noNegocios_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `noNegocios_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `periodo` smallint(5) unsigned NOT NULL DEFAULT '0',
  `porAcotamiento` float NOT NULL DEFAULT '0',
  `porbonoGanado_1` float NOT NULL DEFAULT '0',
  `porbonoGanado_2` float NOT NULL DEFAULT '0',
  `porbonoGanado_3` float NOT NULL DEFAULT '0',
  `porbonoGanado_4` float NOT NULL DEFAULT '0',
  `porcentajeConservacion_1` float NOT NULL DEFAULT '0',
  `porcentajeConservacion_2` float NOT NULL DEFAULT '0',
  `porcentajeConservacion_3` float NOT NULL DEFAULT '0',
  `porcentajeConservacion_4` float NOT NULL DEFAULT '0',
  
  `porsiniestridad_1` float NOT NULL DEFAULT '0',
  `porsiniestridad_2` float NOT NULL DEFAULT '0',
  `porsiniestridad_3` float NOT NULL DEFAULT '0',
  `porsiniestridad_4` float NOT NULL DEFAULT '0',

  `primasnetasiniciales` float NOT NULL DEFAULT '0',

  `primas_promedio` float NOT NULL DEFAULT '0',
  `primaspromedio` float NOT NULL DEFAULT '0',

  `primasAfectasInicialesPagar_1` float NOT NULL DEFAULT '0',
  `primasAfectasInicialesPagar_2` float NOT NULL DEFAULT '0',
  `primasAfectasInicialesPagar_3` float NOT NULL DEFAULT '0',
  `primasAfectasInicialesPagar_4` float NOT NULL DEFAULT '0',
  `primasAfectasInicialesUbicar` float NOT NULL DEFAULT '0',
  `primasRenovacion_1` float NOT NULL DEFAULT '0',
  `primasRenovacion_2` float NOT NULL DEFAULT '0',
  `primasRenovacion_3` float NOT NULL DEFAULT '0',
  `primasRenovacion_4` float NOT NULL DEFAULT '0',
  `primasRenovacionPagar_1` float NOT NULL DEFAULT '0',
  `primasRenovacionPagar_2` float NOT NULL DEFAULT '0',
  `primasRenovacionPagar_3` float NOT NULL DEFAULT '0',
  `primasRenovacionPagar_4` float NOT NULL DEFAULT '0',
  `saves` tinyint(3) unsigned NOT NULL DEFAULT '0',

  `simulatorIngresosPeriod_1` float NOT NULL DEFAULT '0',
  `simulatorIngresosPeriod_2` float NOT NULL DEFAULT '0',
  `simulatorIngresosPeriod_3` float NOT NULL DEFAULT '0',
  `simulatorIngresosPeriod_4` float NOT NULL DEFAULT '0',

  `simulatoringresoscuartotrimestre` float NOT NULL DEFAULT '0',
  `simulatoringresosprimertrimestre` float NOT NULL DEFAULT '0',
  `simulatoringresossegundotrimestre` float NOT NULL DEFAULT '0',
  `simulatoringresostercertrimestre` float NOT NULL DEFAULT '0',

  `simulatorPrimasPeriod_1` float NOT NULL DEFAULT '0',
  `simulatorPrimasPeriod_2` float NOT NULL DEFAULT '0',
  `simulatorPrimasPeriod_3` float NOT NULL DEFAULT '0',
  `simulatorPrimasPeriod_4` float NOT NULL DEFAULT '0',  

  `simulatorprimascuartotrimestre` float NOT NULL DEFAULT '0',
  `simulatorprimasprimertrimestre` float NOT NULL DEFAULT '0',
  `simulatorprimassegundotrimestre` float NOT NULL DEFAULT '0',
  `simulatorprimastercertrimestre` float NOT NULL DEFAULT '0',
  `XAcotamiento_1` float NOT NULL DEFAULT '0',
  `XAcotamiento_2` float NOT NULL DEFAULT '0',
  `XAcotamiento_3` float NOT NULL DEFAULT '0',
  `XAcotamiento_4` float NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `ramo` (`ramo`),
  KEY `agent_id` (`agent_id`),
  KEY `year` (`year`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
